# デプロイしたいディレクトリの設定
[build]
  publish = "/build"

# marge master
[context.branch-name.master]
  command = "yarn && yarn deploy"

[context.branch-deploy]
  command = "yarn && yarn deploy"

# SPA用の設定
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200